language: python
python:
- "2.7.13"
sudo: required

install:
  - |
    git clone https://gerrit.mcp.mirantis.com/salt-formulas/salt-formulas-scripts
    ./salt-formulas-scripts/bootstrap-openstack-kitchen.sh	

env:
  - UBUNTU_DISTRO=xenial SALT_VERSION=2018.3 SUITE=iptables
  - UBUNTU_DISTRO=xenial SALT_VERSION=2017.7 SUITE=iptables
  - UBUNTU_DISTRO=bionic SALT_VERSION=2018.3 SUITE=iptables
  - UBUNTU_DISTRO=bionic SALT_VERSION=2017.7 SUITE=iptables

before_script:
  - set -o pipefail
  - make test | tail

script:
  - test ! -e .kitchen.openstack.yml || bundle exec kitchen converge ${SUITE} || true
  - test ! -e .kitchen.openstack.yml || bundle exec kitchen verify ${SUITE} -t tests/integration

notifications:
  on:
    branch: master
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6123573504759330786b
    on_success: change  # options: [always|never|change] default: always
    on_failure: never  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
    on_cancel: never    # options: [always|never|change] default: always
    on_error: never    # options: [always|never|change] default: always
  email: false
